// Web-optimized data model (generated)
const designs = [
  {
    "id": "characters-2d_character",
    "title": "2D Character Illustrations",
    "category": "Characters",
    "description": "A collection of original 2D character illustrations designed for gaming, mascot branding, and digital media. Each character was developed from concept sketches through to final colored artwork, bringing personality and storytelling to every design. Tools used: Adobe Illustrator, Photoshop.",
    "source": "",
    "thumbnail": "web/assets/characters/characters-2d_character_cover_thumb.jpg",
    "images": [
      "web/assets/characters/characters-2d_character_01.jpg",
      "web/assets/characters/characters-2d_character_02.jpg",
      "web/assets/characters/characters-2d_character_03.jpg"
    ],
    "count": 3
  },
  {
    "id": "posters_banners-bannersposters",
    "title": "Banner & Poster Collection",
    "category": "Posters Banners",
    "description": "A diverse collection of 87 banner and poster designs created for clients across food & beverage, entertainment, automotive, retail, and lifestyle industries. Each piece balances bold visual impact with clear messaging, optimized for both print and digital formats. Tools used: Adobe Photoshop, Illustrator, InDesign.",
    "source": "",
    "thumbnail": "web/assets/posters_banners/posters_banners-bannersposters_cover_thumb.jpg",
    "images": [
      "web/assets/posters_banners/posters_banners-bannersposters_01.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_02.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_03.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_04.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_05.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_06.gif",
      "web/assets/posters_banners/posters_banners-bannersposters_07.gif",
      "web/assets/posters_banners/posters_banners-bannersposters_08.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_09.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_10.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_11.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_12.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_13.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_14.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_15.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_16.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_17.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_18.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_19.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_20.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_21.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_22.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_23.jpg",
      "web/assets/posters_banners/posters_banners-bannersposters_24.jpg"
    ],
    "count": 87
  },
  {
    "id": "branding-logos",
    "title": "Logo Design Collection",
    "category": "Branding",
    "description": "A showcase of 26 logo designs spanning multiple industries — from restaurants and real estate to tech startups and personal brands. Each mark was crafted to be memorable, scalable, and versatile across all media. Tools used: Adobe Illustrator, CorelDraw.",
    "source": "",
    "thumbnail": "web/assets/branding/branding-logos_cover_thumb.jpg",
    "images": [
      "web/assets/branding/branding-logos_01.jpg",
      "web/assets/branding/branding-logos_02.jpg",
      "web/assets/branding/branding-logos_03.jpg",
      "web/assets/branding/branding-logos_04.jpg",
      "web/assets/branding/branding-logos_05.jpg",
      "web/assets/branding/branding-logos_07.jpg",
      "web/assets/branding/branding-logos_08.jpg",
      "web/assets/branding/branding-logos_10.jpg",
      "web/assets/branding/branding-logos_11.jpg",
      "web/assets/branding/branding-logos_12.jpg",
      "web/assets/branding/branding-logos_13.jpg",
      "web/assets/branding/branding-logos_14.jpg",
      "web/assets/branding/branding-logos_15.jpg",
      "web/assets/branding/branding-logos_16.jpg",
      "web/assets/branding/branding-logos_17.jpg",
      "web/assets/branding/branding-logos_18.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_01.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_02.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_03.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_04.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_05.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_06.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_07.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_08.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_09.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_10.jpg"
    ],
    "count": 16
  },
  {
    "id": "motion_graphics-logo_animation",
    "title": "Logo Animation Concepts",
    "category": "Motion Graphics",
    "description": "Logo animation concepts bringing static brand marks to life through motion. Each animation was designed to capture attention in the critical first seconds of video content, social media intros, and brand presentations. Tools used: Adobe After Effects, Premiere Pro.",
    "source": "",
    "thumbnail": "web/assets/motion_graphics/motion_graphics-logo_animation_cover_thumb.jpg",
    "images": [
      "web/assets/motion_graphics/motion_graphics-logo_animation_01.gif"
    ],
    "count": 1
  },
  {
    "id": "posters_banners-calendar_design",
    "title": "Custom Calendar Designs",
    "category": "Posters Banners",
    "description": "A series of 13 custom calendar designs featuring themed monthly layouts with original photography, typography, and seasonal color palettes. Created for corporate gifting and brand merchandising programs. Tools used: Adobe InDesign, Photoshop, Illustrator.",
    "source": "",
    "thumbnail": "web/assets/posters_banners/posters_banners-calendar_design_cover_thumb.jpg",
    "images": [
      "web/assets/posters_banners/posters_banners-calendar_design_01.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_02.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_03.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_04.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_05.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_06.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_07.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_08.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_09.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_10.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_11.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_12.jpg",
      "web/assets/posters_banners/posters_banners-calendar_design_13.jpg"
    ],
    "count": 13
  },
  {
    "id": "motion_graphics-motion_graphic",
    "title": "Motion Graphics Showreel",
    "category": "Motion Graphics",
    "description": "Motion graphic compositions combining kinetic typography, animated illustrations, and dynamic transitions for social media content, event promotions, and brand storytelling. Each piece demonstrates fluid visual storytelling through movement and timing. Tools used: Adobe After Effects, Premiere Pro, Illustrator.",
    "source": "",
    "thumbnail": "web/assets/motion_graphics/motion_graphics-motion_graphic_cover_thumb.jpg",
    "images": [
      "web/assets/motion_graphics/motion_graphics-motion_graphic_01.gif",
      "web/assets/motion_graphics/motion_graphics-motion_graphic_02.gif",
      "web/assets/motion_graphics/motion_graphics-motion_graphic_03.gif",
      "web/assets/motion_graphics/motion_graphics-motion_graphic_04.gif",
      "web/assets/motion_graphics/motion_graphics-motion_graphic_05.gif",
      "web/assets/motion_graphics/motion_graphics-logo_animation_01.gif"
    ],
    "count": 5
  },
  {
    "id": "branding-logo_&_brand_identity",
    "title": "Logo & Brand Identity",
    "category": "Branding",
    "description": "A curated collection of logo and brand identity projects created for clients across food & beverage, entertainment, immigration, and lifestyle sectors. Each logo was designed to capture the brand's essence — from concept sketches to final vector delivery — using Adobe Illustrator and Photoshop. Clients include Tandoori Beatz, CanEuro Migration Services, Decor Builders, Expert Realtors, Radio Mirchi, and more.",
    "source": "",
    "thumbnail": "web/assets/branding/branding-logo_&_brand_identity_cover_thumb.jpg",
    "images": [
      "web/assets/branding/branding-logo_&_brand_identity_01.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_02.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_03.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_04.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_05.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_06.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_07.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_08.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_09.jpg",
      "web/assets/branding/branding-logo_&_brand_identity_10.jpg"
    ],
    "count": 10
  },
  {
    "id": "typography-typography",
    "title": "Typography",
    "category": "Typography",
    "description": "Typography is the art of arranging type to communicate with clarity, personality, and purpose. This collection showcases typographic design work created for a range of real-world briefs — from event posters and radio campaigns to motivational word-art and social content.Each piece explores how letterforms, hierarchy, and layout can carry emotion and meaning on their own. Tools used: Adobe Photoshop, Illustrator, CorelDraw.",
    "source": "",
    "thumbnail": "web/assets/typography/typography-typography_cover_thumb.jpg",
    "images": [
      "web/assets/typography/typography-typography_01.jpg",
      "web/assets/typography/typography-typography_02.jpg",
      "web/assets/typography/typography-typography_03.jpg",
      "web/assets/typography/typography-typography_04.jpg",
      "web/assets/typography/typography-typography_05.jpg",
      "web/assets/typography/typography-typography_06.jpg"
    ],
    "count": 6
  },
  {
    "id": "posters_banners-cmyk_banner",
    "title": "CMYK Banner",
    "category": "Posters Banners",
    "description": "CMYK Banner Design showcases print-ready promotional work produced for real clients across multiple industries — including legal services, agriculture machinery, hospitality, publishing, and events. Each piece was built to professional print specifications using CMYK colour profiles, with careful attention to bleed, typography hierarchy, and brand consistency.Projects span business cards, brochures, catalogues, event banners, and promotional flyers. Tools used: Adobe Photoshop, Illustrator, InDesign, CorelDraw.",
    "source": "",
    "thumbnail": "web/assets/posters_banners/posters_banners-cmyk_banner_cover_thumb.jpg",
    "images": [
      "web/assets/posters_banners/posters_banners-cmyk_banner_01.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_02.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_03.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_04.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_05.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_06.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_07.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_08.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_09.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_10.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_11.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_12.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_13.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_14.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_15.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_16.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_17.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_18.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_19.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_20.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_21.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_22.jpg",
      "web/assets/posters_banners/posters_banners-cmyk_banner_23.jpg"
    ],
    "count": 23
  },
  {
    "id": "posters_banners-digital_banner",
    "title": "Digital Banner",
    "category": "Posters Banners",
    "description": "Digital Banner Design brings together web-ready promotional content created for real clients across diverse sectors — including automotive, hospitality, immigration, retail, and entertainment. Every banner was built for digital platforms: social media, email campaigns, websites, and display advertising.The work spans Facebook covers, promotional ads, event announcements, restaurant specials, and brand awareness creatives. Clients include Hero MotoCorp, CanEuro Migration Services, Bombay Blossom, and more. Tools used: Adobe Photoshop, Illustrator, After Effects.",
    "source": "",
    "thumbnail": "web/assets/posters_banners/posters_banners-digital_banner_cover_thumb.jpg",
    "images": [
      "web/assets/posters_banners/posters_banners-digital_banner_01.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_02.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_03.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_04.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_05.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_06.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_07.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_08.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_09.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_10.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_11.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_12.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_13.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_14.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_15.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_16.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_17.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_18.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_19.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_20.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_21.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_22.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_23.jpg",
      "web/assets/posters_banners/posters_banners-digital_banner_24.jpg"
    ],
    "count": 75
  }
];
export default designs;
